services:
  db:
    image: postgis/postgis:16-3.4
    container_name: buska_db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

    volumes:
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - buska_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: buska_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  buska_data:
