"""adding all notifications columns

Revision ID: 0e3c0d80cb34
Revises: e1d4dadb9200
Create Date: 2026-02-26 19:06:56.464616+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = "0e3c0d80cb34"
down_revision: Union[str, None] = "e1d4dadb9200"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuario", sa.Column("receber_notificacoes", sa.Boolean(), nullable=False))
    op.add_column("viagem", sa.Column("aviso_24h_enviado", sa.Boolean(), nullable=False))
    op.add_column("viagem", sa.Column("aviso_10min_enviado", sa.Boolean(), nullable=False))
    op.add_column(
        "viagem_ponto",
        sa.Column(
            "aviso_aproximacao_enviado", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("viagem_ponto", "aviso_aproximacao_enviado")
    op.drop_column("viagem", "aviso_10min_enviado")
    op.drop_column("viagem", "aviso_24h_enviado")
    op.drop_column("usuario", "receber_notificacoes")
    # ### end Alembic commands ###
