"""move fcm_token to user

Revision ID: 07c64e3bce88
Revises: 25f951eae1bf
Create Date: 2026-02-27 18:16:53.067061+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = "07c64e3bce88"
down_revision: Union[str, None] = "25f951eae1bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aluno", "receber_notificacoes")
    op.drop_column("aluno", "fcm_token")
    op.add_column("usuario", sa.Column("fcm_token", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "fcm_token")
    op.add_column(
        "aluno", sa.Column("fcm_token", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.add_column(
        "aluno",
        sa.Column(
            "receber_notificacoes",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
