"""Add telemetry and fast gps memory

Revision ID: 7f4d9fd81526
Revises: 48c7cf6a20f6
Create Date: 2026-03-02 20:14:12.956137+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = "7f4d9fd81526"
down_revision: Union[str, None] = "48c7cf6a20f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetria_viagem",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("viagem_id", sa.UUID(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=11, scale=8), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["viagem_id"], ["viagem.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telemetria_viagem_viagem_id"), "telemetria_viagem", ["viagem_id"], unique=False
    )
    op.add_column(
        "alunos_confirmados",
        sa.Column("aluno_lat", sa.Numeric(precision=10, scale=8), nullable=True),
    )
    op.add_column(
        "alunos_confirmados",
        sa.Column("aluno_lon", sa.Numeric(precision=11, scale=8), nullable=True),
    )
    op.add_column(
        "alunos_confirmados", sa.Column("aluno_gps_hora", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "viagem", sa.Column("motorista_lat", sa.Numeric(precision=10, scale=8), nullable=True)
    )
    op.add_column(
        "viagem", sa.Column("motorista_lon", sa.Numeric(precision=11, scale=8), nullable=True)
    )
    op.add_column(
        "viagem", sa.Column("motorista_gps_hora", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("viagem", "motorista_gps_hora")
    op.drop_column("viagem", "motorista_lon")
    op.drop_column("viagem", "motorista_lat")
    op.drop_column("alunos_confirmados", "aluno_gps_hora")
    op.drop_column("alunos_confirmados", "aluno_lon")
    op.drop_column("alunos_confirmados", "aluno_lat")
    op.drop_index(op.f("ix_telemetria_viagem_viagem_id"), table_name="telemetria_viagem")
    op.drop_table("telemetria_viagem")
    # ### end Alembic commands ###
