"""expand instituicao for external catalog import

Revision ID: dcc0d379db3c
Revises: b523b7f5667c
Create Date: 2026-04-08 02:37:11.717938+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = 'dcc0d379db3c'
down_revision: Union[str, None] = 'b523b7f5667c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instituicao', sa.Column('fonte', sa.String(length=20), nullable=False))
    op.add_column('instituicao', sa.Column('codigo_externo', sa.String(length=30), nullable=False))
    op.add_column('instituicao', sa.Column('sigla', sa.String(length=30), nullable=True))
    op.add_column('instituicao', sa.Column('uf', sa.String(length=2), nullable=False))
    op.add_column('instituicao', sa.Column('prefeitura_id', sa.UUID(), nullable=False))
    op.add_column('instituicao', sa.Column('situacao', sa.String(length=80), nullable=True))
    op.add_column('instituicao', sa.Column('categoria_administrativa', sa.String(length=50), nullable=True))
    op.add_column('instituicao', sa.Column('organizacao_academica', sa.String(length=50), nullable=True))
    op.alter_column('instituicao', 'ponto_id',
               nullable=True)
    op.create_index(op.f('ix_instituicao_prefeitura_id'), 'instituicao', ['prefeitura_id'], unique=False)
    op.create_index(op.f('ix_instituicao_uf'), 'instituicao', ['uf'], unique=False)
    op.create_unique_constraint('uq_instituicao_fonte_codigo_externo', 'instituicao', ['fonte', 'codigo_externo'])
    op.create_foreign_key(None, 'instituicao', 'prefeitura', ['prefeitura_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instituicao', type_='foreignkey')
    op.drop_constraint('uq_instituicao_fonte_codigo_externo', 'instituicao', type_='unique')
    op.drop_index(op.f('ix_instituicao_uf'), table_name='instituicao')
    op.drop_index(op.f('ix_instituicao_prefeitura_id'), table_name='instituicao')
    op.alter_column('instituicao', 'ponto_id',
               nullable=False)
    op.drop_column('instituicao', 'organizacao_academica')
    op.drop_column('instituicao', 'categoria_administrativa')
    op.drop_column('instituicao', 'situacao')
    op.drop_column('instituicao', 'prefeitura_id')
    op.drop_column('instituicao', 'uf')
    op.drop_column('instituicao', 'sigla')
    op.drop_column('instituicao', 'codigo_externo')
    op.drop_column('instituicao', 'fonte')
    # ### end Alembic commands ###
