"""Adding columns to enable system autochecking

Revision ID: 48c7cf6a20f6
Revises: 07c64e3bce88
Create Date: 2026-03-02 19:50:35.477092+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = "48c7cf6a20f6"
down_revision: Union[str, None] = "07c64e3bce88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alunos_confirmados", sa.Column("embarcou", sa.Boolean(), nullable=False))
    op.add_column(
        "alunos_confirmados", sa.Column("tentativas_auto_checkin", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alunos_confirmados", "tentativas_auto_checkin")
    op.drop_column("alunos_confirmados", "embarcou")
    # ### end Alembic commands ###
