"""add ocorrencia and new user statuses

Revision ID: 7bb68b5bee12
Revises: edd55e85bcdd
Create Date: 2026-04-08 08:27:37.663833+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '7bb68b5bee12'
down_revision: Union[str, None] = 'edd55e85bcdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocorrencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('viagem_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('ATRASO', 'SUPERLOTACAO', 'COMPORTAMENTO', 'CANCELAMENTO', 'OUTRO', name='tipo_ocorrencia'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ABERTA', 'RESOLVIDA', name='status_ocorrencia'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viagem_id'], ['viagem.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ocorrencia_autor', 'ocorrencia', ['autor_id'], unique=False)
    op.create_index('idx_ocorrencia_status', 'ocorrencia', ['status'], unique=False)
    op.create_index('idx_ocorrencia_viagem', 'ocorrencia', ['viagem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ocorrencia_viagem', table_name='ocorrencia')
    op.drop_index('idx_ocorrencia_status', table_name='ocorrencia')
    op.drop_index('idx_ocorrencia_autor', table_name='ocorrencia')
    op.drop_table('ocorrencia')
    # ### end Alembic commands ###
