"""add fcm token to user

Revision ID: 25f951eae1bf
Revises: 0e3c0d80cb34
Create Date: 2026-02-27 13:14:00.693378+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = "25f951eae1bf"
down_revision: Union[str, None] = "0e3c0d80cb34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aluno",
        sa.Column("receber_notificacoes", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column("aluno", sa.Column("fcm_token", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aluno", "fcm_token")
    op.drop_column("aluno", "receber_notificacoes")
    # ### end Alembic commands ###
